CREATE DATABASE IF NOT EXISTS runescape;

USE runescape;

CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS quests (
    quest_id INT AUTO_INCREMENT PRIMARY KEY,
    quest_name VARCHAR(100) NOT NULL,
    quest_description TEXT
);

CREATE TABLE banned (
    player_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    reason VARCHAR(255),
    ban_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    banned_by VARCHAR(50)
);
