-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 23, 2024 at 02:07 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `runescape`
--

-- --------------------------------------------------------

--
-- Table structure for table `banned`
--

CREATE TABLE `banned` (
  `player_id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `ban_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `banned_by` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `quests`
--

CREATE TABLE `quests` (
  `quest_id` int(11) NOT NULL,
  `quest_name` varchar(100) NOT NULL,
  `quest_description` text DEFAULT NULL,
  `quest_guide` text DEFAULT NULL,
  `quest_pic` text DEFAULT NULL,
  `quest_start` text DEFAULT NULL,
  `quest_reward` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `quests`
--

INSERT INTO `quests` (`quest_id`, `quest_name`, `quest_description`, `quest_guide`, `quest_pic`, `quest_start`, `quest_reward`) VALUES
(1, 'Cook\'s Assistant', 'The Lumbridge Castle cook is in a mess. It is the Duke of Lumbridge\'s birthday and the cook is making the cake. He needs a lot of ingredients and doesn\'t have much time.\r\n', 'Objective: The Cook needs help making a cake for the Duke\'s birthday, but he\'s missing a few ingredients.\nIngredients Needed: You\'ll need to gather the following ingredients:\nA bucket of milk (obtainable from a dairy cow)\nA pot of flour (can be bought from the Lumbridge General Store)\nAn egg (can be found by searching the chicken coop near Lumbridge Castle)\nGetting the Ingredients:\nMilk: Head north of Lumbridge Castle to the cow pen and use an empty bucket on a dairy cow to obtain milk.\nFlour: Purchase a pot of flour from the Lumbridge General Store. It\'s located just west of the castle.\nEgg: Go to the chicken coop just east of the castle and search the nest to find an egg.\nCompleting the Quest:\nOnce you have all three ingredients, return to the Cook in Lumbridge Castle\'s kitchen.\nGive him the milk, flour, and egg.\nHe will thank you and reward you with a quest point and some cooking experience.\nQuest Complete: Congratulations! You\'ve completed the Cook\'s Assistant quest. Enjoy your rewards and the satisfaction of helping out the cook.\nThat\'s it! It\'s a straightforward quest that introduces you to some basic game mechanics and gets you started on your adventure in Gielinor.', 'https://oldschool.runescape.wiki/images/thumb/Cook%27s_Assistant.png/300px-Cook%27s_Assistant.png?2e488', 'Start Point: Begin the quest by speaking to Duke Horacio in Lumbridge Castle.', 'https://oldschool.runescape.wiki/images/Cook%27s_Assistant_reward_scroll.png?69721'),
(2, 'Sheep Shearer\r\n', 'Fred the Farmer\'s sheep are getting mighty woolly. He will pay you to shear them.\r\n', 'Objective: Fred needs your help shearing his sheep. He\'ll ask you to shear 20 sheep for him.\nGetting Started: Fred will provide you with some shears, so no need to bring your own.\nShearing the Sheep:\nHead to the field just south of Fred\'s house where you\'ll find plenty of sheep.\nUse the shears on the sheep to collect their wool. You\'ll need to shear 20 sheep in total.\nCompleting the Quest:\nOnce you\'ve sheared 20 sheep, return to Fred the Farmer.\nGive him the wool you\'ve collected.\nQuest Complete:\nFred will thank you for your help and reward you with 60 coins and 150 Crafting experience.\nCongratulations! You\'ve completed the Sheep Shearer quest.\nThat\'s it! It\'s a simple and quick quest that rewards you with some coins and Crafting experience. Enjoy your rewards and the gratitude of Fred the Farmer.\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Sheep_Shearer.png/300px-Sheep_Shearer.png?6e6ad', 'Start Point: Begin the quest by talking to Fred the Farmer in his house located just north of Lumbridge Castle.', 'https://oldschool.runescape.wiki/images/Sheep_Shearer_reward_scroll.png?0d60e'),
(3, 'X Marks the Spot\r\n', 'Veos has long been a lover of treasure hunts and his latest hunt has brought him to Lumbridge. However, not knowing the area well, Veos could use some help finding this treasure.\r\n', 'Objective: Veos will tell you about a treasure map he has found and will ask for your help in deciphering it.\nGetting Started: Accept the quest and obtain the treasure map from Veos.\nDeciphering the Map: Open the map in your inventory and examine it to reveal a clue about the location of the treasure.\nFinding the Location: The map will lead you to a location northeast of the Varrock sawmill. Head there to find a crossroads with a broken cart. Search the nearby bushes to uncover the treasure chest.\nCompleting the Quest:\nOnce you\'ve found the treasure chest, open it to claim your reward.\nReturn to Veos in Port Sarim and speak to him to complete the quest.\nQuest Complete:\nVeos will thank you for your help and reward you with 2000 coins and a beginner clue scroll.\nThat\'s it! \"X Marks the Spot\" is a straightforward quest that introduces you to treasure hunting mechanics in the game. Enjoy your reward and the excitement of uncovering hidden treasures!', 'https://oldschool.runescape.wiki/images/thumb/X_Marks_the_Spot.png/300px-X_Marks_the_Spot.png?2fdc5', 'Start Point: Begin the quest by speaking to Veos, who can be found at the southernmost dock of Port Sarim.', 'https://oldschool.runescape.wiki/images/X_Marks_the_Spot_reward_scroll.png?4ab43'),
(4, 'Pirate\'s Treasure\r\n', 'Redbeard Frank knows the location of pirate treasure, but he\'ll only part with the knowledge for a bottle of Karamjan rum.\r\n', 'Objective: Redbeard Frank will inform you about a treasure chest buried somewhere on the island of Karamja, and he\'ll ask for your help in retrieving it.\nGetting Started: Accept the quest and obtain the white apron from him, which you\'ll need to disguise yourself as a pirate.\nTravel to Karamja: Head to the dock in Port Sarim and speak to the customs officer. Pay the fare to travel to Karamja.\nFinding the Chest: Once you arrive on Karamja, head northwest along the shoreline until you find a banana plantation. Search the crate just outside the house to find a rum bottle.\nObtaining the Key: With the rum bottle in your inventory, head to the Blue Moon Inn located in Varrock. Speak to the bartender and ask about a pirate named Captain Tobias. He\'ll give you a key to the chest.\nReturning to Karamja: Travel back to Karamja and head to the banana plantation again.\nOpening the Chest: Use the key on the chest to open it and claim your reward.\nQuest Complete:\nReturn to Redbeard Frank in Port Sarim and speak to him to complete the quest.\nHe will reward you with a gold ring and some coins.\nThat\'s it! You\'ve successfully completed the \"Pirate\'s Treasure\" quest and uncovered the hidden pirate treasure. Enjoy your rewards and the thrill of adventure on the high seas!', 'https://oldschool.runescape.wiki/images/thumb/Pirate%27s_Treasure.png/300px-Pirate%27s_Treasure.png?a3bf2', 'Start Point: Begin the quest by talking to Redbeard Frank, who can be found in The Rusty Anchor Inn located in Port Sarim.', 'https://oldschool.runescape.wiki/images/Pirate%27s_Treasure_reward_scroll.png?fb224'),
(5, 'Rune Mysteries\r\n', 'Recent research at the Wizards\' Tower has found a way to create Runes for the first time in centuries. Assist the head wizard Sedridor in his research and he too may teach you these secrets!\r\n', 'Objective: The Duke will inform you that the head wizard at the Wizards\' Tower has requested your assistance with a mysterious task.\nGetting Started: Accept the quest and make your way to the Wizards\' Tower, which is located south of Draynor Village.\nSpeaking to Wizard Sedridor: Once inside the Wizards\' Tower, head to the top floor and speak to Wizard Sedridor. He\'ll tell you about a disturbance in the Rune Essence mine and ask you to investigate.\nEntering the Rune Essence Mine: Head down to the basement of the Wizards\' Tower and enter the Rune Essence mine via the portal.\nInvestigating the Disturbance: Explore the mine until you find Aubury, the rune seller. Speak to him and ask about the disturbance.\nCompleting the Task: Aubury will give you a mysterious talisman and ask you to take it back to Wizard Sedridor.\nReturning to Wizard Sedridor: Head back to the top floor of the Wizards\' Tower and speak to Wizard Sedridor. Give him the talisman.\nQuest Complete:\nWizard Sedridor will thank you for your assistance and reward you with the knowledge of Rune essence.\nYou\'ll also receive an Air talisman or access to the Rune essence mine.\nThat\'s it! You\'ve successfully completed the \"Rune Mysteries\" quest and gained access to Rune essence, a crucial component in the world of magic. Enjoy your rewards and the newfound knowledge of runecrafting!', 'https://oldschool.runescape.wiki/images/thumb/Rune_Mysteries.png/300px-Rune_Mysteries.png?7453d', 'Start Point: Begin the quest by speaking to Duke Horacio in Lumbridge Castle.', 'https://oldschool.runescape.wiki/images/Rune_Mysteries_reward_scroll.png?a21ba'),
(6, 'Romeo & Juliet\r\n', 'Romeo and Juliet are desperately in love, but Juliet\'s father doesn\'t approve. Help them to find a way to get married and live happily ever after.\r\n', 'Objective: Romeo will express his love for Juliet but explain that their families are feuding. He\'ll ask for your help in uniting them.\n\nSpeaking to Juliet:\n\nHead to Juliet\'s mansion, located just west of the Varrock west bank.\nSpeak to Juliet on the upper floor balcony and receive a letter for Romeo.\nReturn to Romeo in Varrock Square and deliver the letter to him.\nFather Lawrence:\n\nRomeo suggests seeking advice from Father Lawrence, located in the church northeast of Varrock Square.\nSpeak to Father Lawrence, who mentions a Cadava potion and advises speaking to the Apothecary.\nObtaining the Potion:\n\nVisit the Apothecary in southwestern Varrock, west of the Sword Shop.\nAsk the Apothecary about the quest and obtain a Cadava potion recipe.\nCollect Cadava berries from a bush west of the mine southeast of Varrock.\nReturn to the Apothecary with the berries to receive the Cadava potion.\nAdministering the Potion:\n\nReturn to Juliet and give her the Cadava potion.\nWitness a cutscene where Juliet appears to \"die\" and falls into a coma.\nTo the Crypt:\n\nInform Romeo of Juliet\'s condition and suggest rescuing her from the crypt.\nAccompany Romeo to the crypt, where he becomes infatuated with Juliet\'s cousin, Phillipa.\nQuest Complete:\n\nComplete the quest by successfully guiding Romeo and witnessing the outcome of their encounter in the crypt.\nThat\'s it! You\'ve completed the \"Romeo & Juliet\" quest, bringing resolution to the star-crossed lovers. Enjoy your rewards and the satisfaction of a romantic tale well told!', 'https://oldschool.runescape.wiki/images/thumb/Romeo_%26_Juliet.png/300px-Romeo_%26_Juliet.png?1ac66', 'Start Point: Speak to Romeo in or near Varrock Square to begin the quest.\n', 'https://oldschool.runescape.wiki/images/Romeo_%26_Juliet_reward_scroll.png?8d21d'),
(7, 'The Restless Ghost\r\n', 'A ghost is haunting Lumbridge graveyard. The priest of the Lumbridge church of Saradomin wants you to find out how to get rid of it.\r\n', 'Objective: Father Aereck will inform you that the Lumbridge graveyard has been haunted by a restless ghost, and he needs your help in putting it to rest.\n\nSpeaking to Father Aereck:\n\nFather Aereck can be found in the Lumbridge church, just north of the Lumbridge Castle.\nSpeak to him and agree to help with the ghost problem.\nObtaining the Amulet of Ghostspeak:\n\nFather Aereck will instruct you to speak with Father Urhney, who resides in a small house north of the Lumbridge swamp.\nSpeak to Father Urhney and ask him about the ghost. He\'ll tell you to make an amulet of ghostspeak to communicate with the ghost.\nTo make the amulet, you\'ll need a ball of wool and a sheet. You can obtain the sheet by searching the coffin in the Lumbridge graveyard, and the ball of wool can be obtained by shearing sheep.\nSpeaking to the Restless Ghost:\n\nEquip the amulet of ghostspeak and head to the Lumbridge graveyard.\nFind the restless ghost wandering around the graveyard and speak to him.\nThe ghost will tell you about his skull, which needs to be returned to his coffin to put him to rest.\nFinding the Skull:\n\nHead to the wizard\'s tower located southwest of Lumbridge.\nClimb to the top floor of the tower and search the altar to find the skull.\nReturning the Skull:\n\nReturn to the Lumbridge graveyard and use the skull on the ghost\'s coffin.\nSpeak to the ghost again, and he will thank you for returning his skull, completing the quest.\nQuest Complete:\n\nReturn to Father Aereck in the Lumbridge church and inform him that the ghost has been put to rest.\nFather Aereck will reward you with one quest point, as well as the ability to use the Ectophial teleport to the Ectofuntus.\nThat\'s it! You\'ve successfully completed \"The Restless Ghost\" quest and helped put the spirit to rest. Enjoy your rewards and the peace restored to Lumbridge graveyard!\n\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/The_Restless_Ghost.png/300px-The_Restless_Ghost.png?a05f9', 'Start Point: Speak to Father Aereck in the Lumbridge church to begin the quest.\n\n', 'https://oldschool.runescape.wiki/images/The_Restless_Ghost_reward_scroll.png?5828a'),
(8, 'Prince Ali Rescue\r\n', 'Prince Ali of Al Kharid has been kidnapped by the scheming Lady Keli. You are hired to stage a rescue mission.\r\n', 'Objective: Hassan will inform you that Prince Ali has been kidnapped by Lady Keli, and he needs your help in rescuing him.\n\nSpeaking to Hassan:\n\nVisit the palace in Al Kharid and speak to Hassan, who can be found on the ground floor.\nHe\'ll ask for your assistance in rescuing Prince Ali from his captor, Lady Keli.\nGathering Disguise Items:\n\nHassan will provide you with a wig, skirt, and top to disguise yourself as a woman.\nYou\'ll need to bring a rope to use in the rescue mission.\nFinding Lady Keli\'s Hideout:\n\nHead to the jail located south of the palace and talk to Lady Keli\'s accomplice, Osman.\nHe\'ll inform you that Lady Keli is hiding out in Draynor Manor.\nRescuing Prince Ali:\n\nTravel to Draynor Manor and enter through the back door.\nNavigate through the manor until you find Lady Keli\'s room on the ground floor.\nSpeak to Lady Keli and convince her to release Prince Ali.\nUse the rope on Prince Ali to rescue him from the cell.\nQuest Complete:\n\nReturn to Hassan in the palace in Al Kharid and inform him that you\'ve rescued Prince Ali.\nHassan will reward you with some coins and a quest point for your efforts.\nThat\'s it! You\'ve successfully completed the \"Prince Ali Rescue\" quest and rescued Prince Ali from his captor. Enjoy your rewards and the gratitude of the people of Al Kharid!', 'https://oldschool.runescape.wiki/images/thumb/Prince_Ali_Rescue.png/300px-Prince_Ali_Rescue.png?3bd3b', 'Start Point: Speak to Hassan, located in the palace in Al Kharid.\n\n', 'https://oldschool.runescape.wiki/images/Prince_Ali_Rescue_reward_scroll.png?65170'),
(9, 'Misthalin Mystery\r\n', 'A woman cries as a man lays dying, desperately they beg you to stop a cryptic killer before their friends suffer a similar fate.\r\n', 'Objective: Abigale will inform you that a valuable historical item has gone missing from the Exam Centre, and she needs your help in solving the mystery.\n\nSpeaking to Abigale:\n\nVisit the Exam Centre northeast of the Varrock Museum and speak to Abigale.\nShe\'ll explain that a historical item, the Sword of Raddallin, has disappeared, and she needs your assistance in finding it.\nInvestigating the Scene:\n\nAbigale will provide you with a copy of the archaeological report and ask you to investigate various locations mentioned in the report.\nHead to the locations mentioned in the report, including Varrock Square, the Blue Moon Inn, and the Varrock Museum.\nSpeak to NPCs and search for clues at each location to gather information about the missing sword.\nSolving the Mystery:\n\nPiece together the clues you\'ve gathered to determine the whereabouts of the missing sword.\nReturn to Abigale at the Exam Centre and present your findings to her.\nQuest Complete:\n\nIf you\'ve correctly solved the mystery, Abigale will reward you with some coins and a quest point for your efforts.\nIf you\'re incorrect, she\'ll provide you with more information to help you solve the mystery.\nThat\'s it! You\'ve successfully completed the \"Misthalin Mystery\" quest and helped solve the case of the missing Sword of Raddallin. Enjoy your rewards and the satisfaction of unraveling a historical mystery in Misthalin!', 'https://oldschool.runescape.wiki/images/thumb/Misthalin_Mystery.png/300px-Misthalin_Mystery.png?73d67', 'Start Point: Speak to Abigale, who can be found in the Exam Centre located northeast of the Varrock Museum.\n\n', 'https://oldschool.runescape.wiki/images/Misthalin_Mystery_reward_scroll.png?81958'),
(10, 'Imp Catcher\r\n', 'The Wizard Grayzag has summoned hundreds of little imps. They have stolen a lot of things belonging to the Wizard Mizgog including his magic beads.\r\n', 'Objective: Wizard Mizgog will inform you that imps have stolen his magical beads, and he needs your help in retrieving them.\n\nSpeaking to Wizard Mizgog:\n\nVisit the Wizards\' Tower south of Draynor Village and climb to the top floor to speak to Wizard Mizgog.\nHe\'ll explain that imps have stolen his four magical beads of different colors: red, yellow, black, and white.\nCollecting the Beads:\n\nWizard Mizgog will provide you with a list of locations where imps are known to appear.\nHead to these locations and kill imps until you obtain all four magical beads.\nRed Bead: Imps around the south of Falador.\nYellow Bead: Imps near the chicken coop in Lumbridge.\nBlack Bead: Imps near the Karamja Volcano.\nWhite Bead: Imps in the Wilderness north of Varrock.\nReturning to Wizard Mizgog:\n\nOnce you have obtained all four beads, return to Wizard Mizgog at the top of the Wizards\' Tower.\nGive him the beads, and he will reward you for your efforts.\nQuest Complete:\n\nWizard Mizgog will reward you with an amulet of accuracy and some magic experience.\nCongratulations! You\'ve successfully completed the \"Imp Catcher\" quest and retrieved the stolen magical beads. Enjoy your rewards and newfound magical abilities!\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Imp_Catcher.png/300px-Imp_Catcher.png?87f96', 'Start Point: Speak to Wizard Mizgog, who can be found in the top floor of the Wizards\' Tower south of Draynor Village.', 'https://oldschool.runescape.wiki/images/Imp_Catcher_reward_scroll.png?9b1c5'),
(11, 'Ernest the Chicken\r\n', 'Veronica is very worried. Her fiancé went into the big spooky manor house to ask for directions. An hour later and he\'s still not out yet.\r\n', 'Objective: Veronica will inform you that her fiancé, Ernest, has been turned into a chicken by Professor Oddenstein, and she needs your help in restoring him to his human form.\n\nSpeaking to Veronica:\n\nVisit Draynor Manor northwest of Draynor Village and speak to Veronica.\nShe\'ll explain that her fiancé, Ernest, has gone missing inside the manor after conducting experiments for Professor Oddenstein.\nInvestigating the Manor:\n\nEnter Draynor Manor and search for clues to locate Ernest.\nExplore the manor, solving puzzles and overcoming obstacles to progress further inside.\nRestoring Ernest:\n\nEventually, you\'ll find Ernest trapped in the basement of the manor, transformed into a chicken.\nSpeak to Ernest and find out what happened to him.\nRetrieve the pressure gauge and rubber tube from the shelves in the basement.\nUse the pressure gauge and rubber tube on the pressure machine in the eastern part of the basement to restore Ernest to his human form.\nQuest Complete:\n\nReturn to Veronica outside the manor and inform her that Ernest has been restored.\nVeronica will reward you with some coins and a quest point for your efforts.\nThat\'s it! You\'ve successfully completed the \"Ernest the Chicken\" quest and restored Ernest to his human form. Enjoy your rewards and the satisfaction of a job well done in Draynor Manor!', 'https://oldschool.runescape.wiki/images/thumb/Ernest_the_Chicken.png/300px-Ernest_the_Chicken.png?50f09', 'Start Point: Speak to Veronica, who can be found in Draynor Manor located northwest of Draynor Village.', 'https://oldschool.runescape.wiki/images/Ernest_the_Chicken_reward_scroll.png?c5c58'),
(12, 'Vampyre Slayer\r\n', 'The people of Draynor Village live in constant terror. Their numbers are dwindling, all due to the foul creature lurking in the manor to the north known as a vampyre.\r\n', 'Objective: Morgan will inform you that a vampyre has been terrorizing the village and needs your help in slaying it.\n\nSpeaking to Morgan:\n\nVisit Draynor Village and speak to Morgan, who can be found near the church.\nHe\'ll explain that a vampyre has been attacking villagers and asks for your assistance in defeating it.\nPreparing for the Fight:\n\nMorgan will provide you with a stake and a hammer to use in the battle against the vampyre.\nEnsure you have some food and combat equipment before heading to the fight.\nConfronting the Vampyre:\n\nTravel to the basement of Draynor Manor, located northwest of Draynor Village.\nEnter the basement and navigate to the northwest corner, where you\'ll find the vampyre.\nUse the stake on the vampyre to initiate the fight.\nDefeating the Vampyre:\n\nEngage in combat with the vampyre and defeat it using your combat skills.\nBe sure to keep an eye on your health and use food as necessary to heal.\nQuest Complete:\n\nOnce you\'ve defeated the vampyre, return to Morgan in Draynor Village and inform him of your success.\nMorgan will reward you with some coins and a quest point for your efforts.\nThat\'s it! You\'ve successfully completed the \"Vampyre Slayer\" quest and rid Draynor Village of the vampyre threat. Enjoy your rewards and the gratitude of the villagers!\n\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Vampyre_Slayer.png/300px-Vampyre_Slayer.png?e0b7e', 'Start Point: Speak to Morgan, who can be found in Draynor Village.\n\n', 'https://oldschool.runescape.wiki/images/Vampyre_Slayer_reward_scroll.png?562a2'),
(13, 'Doric\'s Quest\r\n', 'Doric the dwarf is happy to let you use his anvils but first he would like you to run an errand for him.\r\n', 'Objective: Doric will ask you to bring him some materials to help him with his current project.\n\nSpeaking to Doric:\n\nVisit Doric\'s workshop, located north of Falador and west of the Taverley gate.\nSpeak to Doric and ask if he has any quests available.\nDoric will explain that he needs some materials for his project and will ask for your help.\nGathering Materials:\n\nDoric will request you to bring him six clay, four copper ore, and two iron ore.\nIf you don\'t have the materials already, you can mine them nearby:\nClay: Can be mined southwest of Doric\'s workshop, near the Taverley gate.\nCopper Ore: Can be mined at the Dwarven Mine south of Falador.\nIron Ore: Can also be mined at the Dwarven Mine.\nReturning to Doric:\n\nOnce you have all the required materials, return to Doric at his workshop.\nGive him the materials, and he will thank you for your help.\nQuest Complete:\n\nDoric will reward you with 180 coins and 1,300 Mining experience.\nCongratulations! You\'ve successfully completed Doric\'s Quest and helped him with his project. Enjoy your rewards and newfound Mining experience!\nThat\'s it! You\'ve successfully completed Doric\'s Quest. Enjoy your rewards and newfound Mining experience!\n\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Doric%27s_Quest.png/300px-Doric%27s_Quest.png?0f9ed', 'Start Point: Speak to Doric, who can be found in his workshop north of Falador.\n\n', 'https://oldschool.runescape.wiki/images/Doric%27s_Quest_reward_scroll.png?a47d2'),
(14, 'Black Knights\' Fortress\r\n', 'The Black Knights are up to no good. You are hired by the white knights to spy on them and destroy their secret weapon.\r\n', 'Objective: Sir Amik Varze will ask you to infiltrate the Black Knights\' Fortress and gather intelligence.\n\nSpeaking to Sir Amik Varze:\n\nVisit Sir Amik Varze in the White Knights\' Castle courtyard in Falador.\nSpeak to him and ask if he has any quests available.\nSir Amik Varze will explain that the Black Knights are up to no good, and he needs your help in investigating.\nInfiltrating the Fortress:\n\nTravel to the Black Knights\' Fortress, which is located north-west of Falador.\nEnter the fortress and make your way to the top floor.\nGathering Intelligence:\n\nSearch the various rooms on the top floor to find information about the Black Knights\' plans.\nBe careful to avoid the patrolling Black Knights, as they will attack you if they spot you.\nFinding the Secret Plans:\n\nSearch the cupboard in the north-west room of the top floor to find the secret plans.\nOnce you have the plans, return to Sir Amik Varze in the White Knights\' Castle courtyard.\nQuest Complete:\n\nPresent the secret plans to Sir Amik Varze.\nSir Amik Varze will reward you with 3 quest points and access to the White Knights\' Castle.\nCongratulations! You\'ve successfully completed the \"Black Knights\' Fortress\" quest and thwarted the Black Knights\' plans. Enjoy your rewards and the gratitude of the White Knights!\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Black_Knights%27_Fortress.png/300px-Black_Knights%27_Fortress.png?73c5f', 'Start Point: Speak to Sir Amik Varze in the White Knights\' Castle courtyard in Falador.\n\n', 'https://oldschool.runescape.wiki/images/Black_Knights%27_Fortress_reward_scroll.png?c451f'),
(15, 'Shield of Arrav\r\n', 'Varrockian literature tells of a valuable shield, stolen long ago from the museum of Varrock, by a gang of professional thieves. See if you can track down this shield and return it to the museum. You will need a friend to help you complete this quest.\r\n', 'Objective: Reldo will inform you about the Shield of Arrav, which has been stolen, and he needs your help in recovering it.\n\nSpeaking to Reldo:\n\nVisit Reldo in Varrock Palace and ask him if he has any quests available.\nReldo will explain that the Shield of Arrav has been stolen, and he needs your help in retrieving it.\nJoining a Gang:\n\nDecide whether you want to join the Phoenix Gang or the Black Arm Gang.\nThe Phoenix Gang can be joined by speaking to Straven in the Phoenix Gang Hideout located in the southern part of Varrock.\nThe Black Arm Gang can be joined by speaking to Katrine in the Black Arm Gang Hideout located in the south-western part of Varrock.\nCompleting Gang Tasks:\n\nOnce you\'ve joined a gang, complete the tasks assigned to you by your gang leader.\nThese tasks may involve stealing items or performing other illicit activities.\nRecovering the Shield:\n\nWork together with another player who is a member of the opposing gang to retrieve the Shield of Arrav.\nIf you don\'t have a partner, you can join the \"Osrs Soa\" clan chat in-game to find someone to partner with.\nReturning to Reldo:\n\nOnce you\'ve recovered the Shield of Arrav, return to Reldo in Varrock Palace.\nPresent the shield to Reldo to complete the quest.\nQuest Complete:\n\nReldo will reward you with quest points and possibly other rewards depending on your progress in the quest.\nCongratulations! You\'ve successfully completed the \"Shield of Arrav\" quest and helped recover the stolen shield. Enjoy your rewards and the gratitude of Varrock!\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Shield_of_Arrav.png/300px-Shield_of_Arrav.png?02c29', 'Start Point: Speak to Reldo, the librarian located in Varrock Palace.\n\n', 'https://oldschool.runescape.wiki/images/Shield_of_Arrav_reward_scroll.png?809e7'),
(16, 'Demon Slayer\r\n', 'A mighty demon is being summoned to destroy the city of Varrock. You find out you are the one destined to stop him (or at least try).\r\n', 'Objective: Gypsy Aris will inform you about a demon named Delrith that is threatening Varrock, and she needs your help in defeating it.\n\nSpeaking to Gypsy Aris:\n\nVisit Gypsy Aris in her tent south of Varrock and ask her if she has any quests available.\nGypsy Aris will explain that the demon Delrith is threatening Varrock, and she needs your help in defeating it.\nEquipping Silverlight:\n\nGypsy Aris will provide you with Silverlight, a powerful sword capable of harming demons.\nEquip Silverlight before proceeding with the quest.\nConfronting Delrith:\n\nTravel to the stone circle located north of Varrock and speak to Sir Prysin.\nSir Prysin will inform you that you need the help of three heroic items to defeat Delrith: a silver pot, a holy symbol, and a garlic.\nGathering the Items:\n\nThe Silver Pot can be obtained by searching the cupboard in the kitchen of the Blue Moon Inn located in Varrock.\nThe Holy Symbol can be obtained by searching the drawers in Father Lawrence\'s room in the church east of Varrock Palace.\nThe Garlic can be obtained by searching the crates in the kitchen of Morgan\'s house located in Draynor Village.\nConfronting Delrith (Continued):\n\nOnce you have all three items, return to Sir Prysin at the stone circle north of Varrock.\nUse Silverlight on the incantation symbol drawn on the ground to summon Delrith.\nEngage in combat with Delrith and defeat it using Silverlight.\nQuest Complete:\n\nOnce Delrith is defeated, return to Gypsy Aris in her tent south of Varrock.\nGypsy Aris will reward you with quest points and other rewards for your efforts.\nCongratulations! You\'ve successfully completed the \"Demon Slayer\" quest and saved Varrock from the threat of Delrith. Enjoy your rewards and the gratitude of the citizens!', 'https://oldschool.runescape.wiki/images/thumb/Demon_Slayer.png/300px-Demon_Slayer.png?e2760', 'Start Point: Speak to Gypsy Aris in her tent located south of Varrock.\n\n', 'https://oldschool.runescape.wiki/images/Demon_Slayer_reward_scroll.png?8ec7a'),
(17, 'Below Ice Mountain\r\n', 'Willow, an energetic archaeologist (perhaps suspiciously so) is hunting for her next big discovery. She believes she has found the entrance to ancient underground ruins found to the west of Ice Mountain. There\'s a catch though - the entrance is sealed tight and she needs to re-unite her old crew to help her break in. Naturally, she has to stay close to the ruins in order to lay claim to the find, so it falls to you to bring her rag-tag group back together for one last caper and a final big pay-off.\r\nBurntof is an old dwarf with a penchant for demolition, Checkal is a well-built lifter of heavy things and Marley is a cunning thief with a knack for disarming traps.\r\n\r\nTogether, they have the talents it will take to gain entry to the secret ruins. But persuading them might not be easy. See, the gang aren\'t all too keen on working with Willow again, and her intentions might not be as honourable as she claims...', 'Objective:\nThe objective of Below Ice Mountain is to explore the underground area beneath Ice Mountain, which was introduced as part of the \"What Lies Below\" quest.\nExploring the Area:\nOnce you\'ve spoken to Freda, head inside the entrance to the Dwarven Mine.\nFollow the path downwards until you reach the entrance to the newly discovered area beneath Ice Mountain.\nExplore the various caverns and tunnels to uncover secrets, mine ores, and interact with the environment.\nCompleting Tasks:\nAs you explore Below Ice Mountain, you may encounter various tasks or activities to complete.\nThese tasks could involve mining specific ores, solving puzzles, or interacting with NPCs found in the area.\nRewards:\nWhile Below Ice Mountain does not have a specific quest completion or rewards, you may find valuable resources such as ores and gems during your exploration.\nAdditionally, completing certain tasks or activities may grant you experience in various skills.\nExiting:\nWhen you\'re ready to leave Below Ice Mountain, simply return to the entrance to the Dwarven Mine and exit back to the surface.\nOptional:\nIf you\'re interested in additional lore or backstory, you can speak to NPCs found within the area to learn more about its history and inhabitants.\nThat\'s it! Enjoy your exploration of Below Ice Mountain and uncovering its secrets!\n\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Below_Ice_Mountain.png/300px-Below_Ice_Mountain.png?be889', 'Start Point:\nBegin the miniquest by speaking to Freda, located just outside the entrance to the Dwarven Mine north of Falador.', 'https://oldschool.runescape.wiki/images/Below_Ice_Mountain_reward_scroll.png?367fd'),
(18, 'The Knight\'s Sword\r\n', 'Sir Vyvin\'s squire is in trouble. He has accidentally lost Sir Vyvin\'s ceremonial sword. Help him find a replacement without Sir Vyvin finding out.\r\n', 'Objective: The Squire will inform you that Sir Vyvin\'s sword has been lost, and he needs your help in making a replacement.\n\nSpeaking to the Squire:\n\nVisit the White Knights\' Castle in Falador and speak to the Squire in the courtyard.\nHe\'ll explain that Sir Vyvin\'s sword has been lost and ask for your assistance in making a replacement.\nFinding the Imcando Dwarf:\n\nHead to the Dwarven Mines, which are located under Falador.\nSearch for an Imcando dwarf named Thurgo. He can be found in a small building north of Falador, near Mudskipper Point.\nObtaining the Special Ore:\n\nSpeak to Thurgo and ask him about making a sword.\nHe\'ll agree to help but will need a special kind of ore called blurite.\nTravel to the Asgarnian Ice Dungeon, which is located north of Mudskipper Point, and mine some blurite ore.\nSmithing the Sword:\n\nReturn to Thurgo with the blurite ore.\nHe\'ll agree to make the sword but will need a picture of it to work from.\nObtain a picture of the sword by speaking to Reldo in Varrock Palace Library.\nCompleting the Sword:\n\nReturn to Thurgo with the picture of the sword.\nHe\'ll use the blurite ore to make a new sword.\nOnce the sword is complete, take it to the Squire in the White Knights\' Castle.\nQuest Complete:\n\nPresent the sword to the Squire.\nThe Squire will reward you with quest points and other rewards for your efforts.\nCongratulations! You\'ve successfully completed \"The Knight\'s Sword\" quest and helped replace Sir Vyvin\'s lost sword. Enjoy your rewards and the gratitude of the White Knights!\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/The_Knight%27s_Sword.png/300px-The_Knight%27s_Sword.png?53e55', 'Start Point: Speak to the Squire in the courtyard of the White Knights\' Castle in Falador.\n\n', 'https://oldschool.runescape.wiki/images/The_Knight%27s_Sword_reward_scroll.png?95e1e'),
(19, 'Witch\'s Potion\r\n', 'Become one with your darker side. Tap into your hidden depths of magical potential by making a potion with the help of Hetty the Rimmington witch.\r\n', 'Objective: Hetty will ask you to help her brew a potion, and she\'ll provide you with the ingredients needed.\n\nSpeaking to Hetty:\n\nVisit Hetty\'s house in Rimmington and speak to her.\nShe\'ll explain that she needs help brewing a potion and will ask for your assistance.\nGathering Ingredients:\n\nHetty will ask you to gather the following ingredients: eye of newt, rat\'s tail, and onion.\nEye of newt can be purchased from various magic shops across Gielinor, such as Betty\'s Magic Emporium in Port Sarim.\nRat\'s tail can be obtained by killing rats, which are commonly found in various locations throughout Gielinor.\nOnions can be obtained by picking them from fields or purchasing them from a food shop.\nBrewing the Potion:\n\nOnce you\'ve gathered all the ingredients, return to Hetty\'s house in Rimmington.\nUse the ingredients on the cauldron inside Hetty\'s house to brew the potion.\nQuest Complete:\n\nOnce the potion is brewed, speak to Hetty again.\nHetty will reward you with some experience points in Magic and a quest point for your efforts.\nCongratulations! You\'ve successfully completed the \"Witch\'s Potion\" quest and helped Hetty brew her potion. Enjoy your rewards and newfound knowledge of potion-making!', 'https://oldschool.runescape.wiki/images/thumb/Witch%27s_Potion.png/300px-Witch%27s_Potion.png?6151e', 'Start Point: Speak to Hetty the witch, who can be found in her house located in Rimmington.\n\n', 'https://oldschool.runescape.wiki/images/Witch%27s_Potion_reward_scroll.png?76438'),
(20, 'The Corsair Curse\r\n', 'From the newly revealed town of Corsair Cove, deep in the south of Feldip Hills, the captain of the Corsairs has sailed to Port Sarim seeking help. His crew is sick, and he suspects that a curse has been laid upon them. If you can unravel the fearful and conflicting tales of ogre relics, vengeful mermaids and demonic possession, maybe you can help his ailing crew overcome The Corsair Curse.\r\n', 'Objective: Captain Tock will inform you that his crew has been cursed, and he needs your help in finding a way to lift it.\n\nSpeaking to Captain Tock:\n\nVisit Captain Tock on the docks of Corsair Cove, which is located on the northern coast of Feldip Hills.\nSpeak to him and ask if he has any quests available.\nCaptain Tock will explain that his crew has been cursed, and he needs your help in finding a way to lift it.\nInvestigating the Island:\n\nExplore Corsair Cove and talk to various NPCs to gather information about the curse.\nSpeak to various members of the crew, as well as any other NPCs you encounter on the island.\nFinding the Witch:\n\nOne of the crew members will mention a witch who lives on the island and may be able to help.\nSearch the island until you find the witch\'s hut, which is located northwest of the cove.\nLifting the Curse:\n\nSpeak to the witch and ask her about the curse.\nThe witch will inform you that you\'ll need to gather some items to lift the curse: a seagull wing, a lock of hair from a mermaid, and a piece of an old pirate flag.\nGathering the Items:\n\nObtain a seagull wing by killing seagulls on the island.\nObtain a lock of hair from a mermaid by killing one in the water around the island.\nObtain a piece of an old pirate flag by searching around the shipwrecks on the island.\nReturning to the Witch:\n\nOnce you have all three items, return to the witch\'s hut and give them to her.\nThe witch will use the items to create a potion to lift the curse.\nQuest Complete:\n\nSpeak to Captain Tock and inform him that the curse has been lifted.\nCaptain Tock will reward you with some coins and other rewards for your efforts.\nCongratulations! You\'ve successfully completed \"The Corsair Curse\" quest and helped Captain Tock lift the curse from his crew. Enjoy your rewards and the gratitude of the Corsair Cove inhabitants!', 'https://oldschool.runescape.wiki/images/thumb/The_Corsair_Curse.png/300px-The_Corsair_Curse.png?cbea3', 'Start Point: Speak to Captain Tock, who can be found on the docks of Corsair Cove.\n\n', 'https://oldschool.runescape.wiki/images/The_Corsair_Curse_reward_scroll.png?1e9ca'),
(21, 'Goblin Diplomacy\r\n', 'There\'s a disturbance in the Goblin Village. Help the goblins solve their dispute so the world doesn\'t have to worry about rioting goblins. Aim: to help the goblins decide which colour they will wear.\r\n', 'Objective: The generals will ask you to help them resolve a dispute over the color of their armor by finding an alternative solution.\n\nSpeaking to the Generals:\n\nVisit Goblin Village, which is located north of Falador and west of the Crafting Guild.\nSpeak to Generals Bentnoze and Wartface and ask them if they need any help.\nThey\'ll explain that they\'re arguing over the color of their armor and need your help to resolve the dispute.\nInvestigating the Situation:\n\nSpeak to each of the generals individually to learn more about their preferences.\nThey\'ll tell you that one prefers the color red and the other prefers the color green.\nFinding a Solution:\n\nHead to the nearby Lumber Yard and speak to the Sawmill Operator.\nAsk the Sawmill Operator if he has any ideas for how to resolve a dispute over colors.\nHe\'ll suggest that you create an alternative color by mixing blue and yellow.\nCreating the Dye:\n\nObtain some blue dye by purchasing it from Aggie the Witch in Draynor Village or making it yourself with woad leaves and coins.\nObtain some yellow dye by purchasing it from Aggie or making it yourself with onions and coins.\nMix the blue and yellow dyes together to create green dye.\nPresenting the Solution:\n\nReturn to Goblin Village with the green dye.\nUse the green dye on one of the generals\' armor sets to create a compromise color.\nShow the generals the newly dyed armor to resolve their dispute.\nQuest Complete:\n\nThe generals will be pleased with the compromise and reward you with some coins and other rewards.\nCongratulations! You\'ve successfully completed the \"Goblin Diplomacy\" quest and helped bring peace to Goblin Village. Enjoy your rewards and the gratitude of the goblin generals!\n\n\n\n\n\n', 'https://oldschool.runescape.wiki/images/thumb/Goblin_Diplomacy.png/300px-Goblin_Diplomacy.png?79332', 'Start Point: Speak to the Generals Bentnoze and Wartface, who can be found in Goblin Village.\n\n', 'https://oldschool.runescape.wiki/images/Goblin_Diplomacy_reward_scroll.png?ef679'),
(22, 'Dragon Slayer I\r\n', 'Prove yourself a true champion. Kill the mighty dragon Elvarg of Crandor and earn the right to buy and wear the Rune platebody.\r\n', 'Objective: The Guildmaster will inform you that a powerful dragon named Elvarg is terrorizing the village of Crandor, and he needs your help in slaying it.\n\nSpeaking to the Guildmaster:\n\nVisit the Champions\' Guild, located south of Varrock, and speak to the Guildmaster.\nHe\'ll explain that a powerful dragon named Elvarg is terrorizing the village of Crandor, and he needs your help in slaying it.\nGathering the Required Items:\n\nThe Guildmaster will tell you that you\'ll need a map of Crandor, anti-dragon shield, and some food for the journey.\nObtain a map of Crandor from Melzar the Mad\'s Maze, which is located northwest of Rimmington.\nObtain an anti-dragon shield from Oziach, who can be found in Edgeville.\nStock up on food, as the journey to Crandor will be dangerous.\nPreparing for the Journey:\n\nOnce you have all the required items, return to the Champions\' Guild and speak to the Guildmaster.\nHe\'ll give you a boat ride to Crandor.\nSlaying Elvarg:\n\nMake your way through Crandor to reach the entrance of Elvarg\'s lair.\nEquip your anti-dragon shield before entering the lair to protect yourself from Elvarg\'s fiery breath.\nEngage in combat with Elvarg and defeat it using your combat skills and anti-dragon shield.\nQuest Complete:\n\nOnce Elvarg is defeated, return to the Guildmaster in the Champions\' Guild.\nThe Guildmaster will reward you with quest points and other rewards for your efforts.\nCongratulations! You\'ve successfully completed the \"Dragon Slayer\" quest and saved the village of Crandor from the threat of Elvarg. Enjoy your rewards and the gratitude of the Guildmaster!', 'https://oldschool.runescape.wiki/images/thumb/Dragon_Slayer.png/300px-Dragon_Slayer.png?92244', 'Start Point: Speak to the Guildmaster in the Champions\' Guild, which is located south of Varrock.\n\n', 'https://oldschool.runescape.wiki/images/Dragon_Slayer_reward_scroll.png?5517f');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `username`, `password`) VALUES
(31, 'Mark', 'wordpass123');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `banned`
--
ALTER TABLE `banned`
  ADD PRIMARY KEY (`player_id`);

--
-- Indexes for table `quests`
--
ALTER TABLE `quests`
  ADD PRIMARY KEY (`quest_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `banned`
--
ALTER TABLE `banned`
  MODIFY `player_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;

--
-- AUTO_INCREMENT for table `quests`
--
ALTER TABLE `quests`
  MODIFY `quest_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
